name: Setup ucacher
description: Installs the ucacher binary
branding:
  icon: "sunrise"
  color: "green"
author: Earthly technologies

runs:
  using: "composite"
  steps:
    - name: Downloading ucacher binary
      run: |
        echo "Downloading binary from ${{ inputs.binary-url }}"
        mkdir -p /tmp/ucacher/bin
        curl -L https://github.com/earthly/actions-ucacher/raw/refs/heads/main/bin/ucacher -o /tmp/ucacher/bin/ucacher
        chmod +x /tmp/ucacher/bin/ucacher;
        echo "ucacher downloaded to /tmp/ucacher/bin/ucacher";
      shell: bash

    - name: Adding required env vars for cache
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])

    - name: Creating ucacher wrapper
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        echo $GITHUB_REPOSITORY; \
        echo $GITHUB_TOKEN; \
        echo '#!/bin/bash
        UCACHER_DB_FROM_FILESTORAGE=true \
        UCACHER_FS_URI=gha:// \
        UCACHER_TAR_OUTPUTS=true \
        UCACHER_INSTRUMENTER=seccomp_cgo  \
        GITHUB_REPOSITORY=${{ github.repository }} \
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
        UCACHER_SHOW_IO=true \
        FORCE_COLOR=1 \
        LOG_LEVEL=debug \
        /tmp/ucacher/bin/ucacher "$@"' > /usr/local/bin/ucacher;
        chmod +x /usr/local/bin/ucacher;
        echo "ucacher installed at /usr/local/bin/ucacher";
      shell: bash


